### ISSUE TITLE
Malformed GitHub URLs

### ISSUE THREAD

**Issue by marshally** [tenable/terrascan-action#55]
I have added the `terrascan-action` workflow to my GitHub repo using the yaml included at the bottom of this Issue report.

When these render in the GitHub UI, there is no preview.
![image](https://user-images.githubusercontent.com/132798/166343731-6e93c3be-d0a8-4584-a3e7-3e24dbc41f37.png)

I think this is because the URIs in my SARIF file are mangled. They look like `file://https://github.com/myOrg/myRepo`.

```javascript
         "locations": [
            {
              "physicalLocation": {
                "artifactLocation": {
                  "uri": "file://https://github.com/xxx/yyy"
                },
                "region": {
                  "startLine": 50
                }
              },
              "logicalLocations": [
                {
                  "name": "quota_processor_lambda",
                  "kind": "aws_lambda_function"
                }
              ]
            }
          ]
```

The specific command being executed is

```bash
terrascan scan  -d . -i terraform --iac-version v14 -t aws --repo-url https://github.com/xxx/yyy.git --repo-ref refs/pull/124/merge -o sarif
```

When I look to the underlying source, I found that there's a parameter `-o github-sarif` that might be helpful, but when I forked this repo it didn't seem to make a difference.

```yaml
name: terrascan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: accurics/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v14'
        policy_type: 'aws'
        only_warn: true
        sarif_upload: true
        scm_token: ${{ secrets.ACCESS_TOKEN }}

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif
```
