### ISSUE TITLE
github/codeql-action/upload-sarif@v2 upload file failed

### ISSUE THREAD

**Issue by nooperpudd** [tenable/terrascan-action#66]
```yaml 
steps:
    - name: setup terrascan
      # https://github.com/tenable/terrascan-action
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'terraform'
        iac_version: 'v15'
        policy_type: 'aws'
        only_warn: true
        iac_dir: "./infra/module"
        sarif_upload: true

    - name: Upload SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: terrascan.sarif
        category: terrascan
```
error message:

Analysis upload status is pending.
[183](https://github.com/startuplcoud/infra-multi-account-region-startup-kit/runs/6960000259?check_suite_focus=true#step:3:188)
  Analysis upload status is failed.
[184](https://github.com/startuplcoud/infra-multi-account-region-startup-kit/runs/6960000259?check_suite_focus=true#step:3:189)
  Error: Code Scanning could not process the submitted SARIF file:
[185](https://github.com/startuplcoud/infra-multi-account-region-startup-kit/runs/6960000259?check_suite_focus=true#step:3:190)
  SARIF URI scheme "git" did not match the checkout URI scheme "file",
[186](https://github.com/startuplcoud/infra-multi-account-region-startup-kit/runs/6960000259?check_suite_focus=true#step:3:191)
  Error: Code Scanning could not process the submitted SARIF file:
[187](https://github.com/startuplcoud/infra-multi-account-region-startup-kit/runs/6960000259?check_suite_focus=true#step:3:192)
  SARIF URI scheme "git" did not match the checkout URI scheme "file",
[188](https://github.com/startuplcoud/infra-multi-account-region-startup-kit/runs/6960000259?check_suite_focus=true#step:3:193)
      at Object.waitForProcessing (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-lib.js:334:19)
[189](https://github.com/startuplcoud/infra-multi-account-region-startup-kit/runs/6960000259?check_suite_focus=true#step:3:194)
      at async run (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:59:13)
[190](https://github.com/startuplcoud/infra-multi-account-region-startup-kit/runs/6960000259?check_suite_focus=true#step:3:195)
      at async runWrapper (/home/runner/work/_actions/github/codeql-action/v2/lib/upload-sarif-action.js:74:9)
