### ISSUE TITLE
Wrong detection of AllowPrivilegeEscalation and others

### ISSUE THREAD

**Issue by areplogle-reverb** [tenable/terrascan-action#68]
Seems to be a clone of this issue: https://github.com/tenable/terrascan/issues/721

Which is resolved through proper terrascan init and pulling down the latest policy files. How can I ensure thats happening in the GH action? I'm getting this hundreds of times along with false positives on `Prefer using secrets as files over secrets as environment variables`

Example Result:
```
	-----------------------------------------------------------------------
	
	Description    :	Containers Should Not Run with AllowPrivilegeEscalation
	File           :	helm/workloads/lab/datadog/manifest.yaml
	Line           :	916
	Severity       :	HIGH
```

Example Source:
```
<...starting at line 916...>
---
# Source: datadog/templates/agent-services.yaml
apiVersion: v1
kind: Service

metadata:
  name: datadog
  namespace: datadog
  labels:
    app: "datadog"
    chart: "datadog-2.37.4"
    release: "datadog"
    heritage: "Helm"
    helm.sh/chart: 'datadog-2.37.4'
    app.kubernetes.io/name: "datadog"
    app.kubernetes.io/instance: "datadog"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "7"
    <...>
  ````

**Comment by areplogle-reverb** [comment]
My action yaml

```
on: [push]

jobs:
  terrascan_job:
    runs-on: ubuntu-latest
    name: terrascan-action
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run Terrascan
      id: terrascan
      uses: tenable/terrascan-action@main
      with:
        iac_type: 'k8s'
        iac_version: 'v1'
        policy_type: 'k8s'
        only_warn: true
        #scm_token: ${{ secrets.GH_ACCESS_TOKEN }}
        #verbose: true
        #sarif_upload: true
        #non_recursive:
        #iac_dir:
        #policy_path:
        #skip_rules:
        config_path:  /github/workspace/.github/workflows/config.toml
        #find_vulnerabilities:
        #webhook_url:
        #webhook_token:
```

**Comment by gaurav-gogia** [comment]
Hi @areplogle-reverb terrascan initialises by cloning itself in `$HOME/.terrascan` dir by default. And the terrascan action seems to be running `terrascan init` as the first operation. 

https://github.com/tenable/terrascan-action/blob/main/Dockerfile

Could you please verify your configuration to see where terrascan is being initialised and if it is an accessible dir.

**Comment by areplogle-reverb** [comment]
@gaurav-gogia Thank you :)  I'm not clear what you're asking though. Based on the dockerfile you referenced the policy files are in the docker image itself, not initialized into some directory where the GH action is executing?

`build tenable/terrascan-action@main` does execute and the step for init processes without issue:
```
<...>
  Step 4/7 : COPY --from=terrascan /go/bin/terrascan /usr/bin/
   ---> 3fd2e6b3a117
  Step 5/7 : RUN terrascan init
   ---> Running in 4cf39eab5b06
  Removing intermediate container 4cf39eab5b06
   ---> 26f3963ba14d
<...>
  ```

**Comment by areplogle-reverb** [comment]
@gaurav-gogia ah ok, yes when the docker container builds, the init process executes successfully and seems to initialize into the container 👍

**Comment by gaurav-gogia** [comment]
@areplogle-reverb 

I see. Could you please share some sample code where you notice those policy violations but don't expect the violations to occur? 

I'll try to recreate the scenario and get back to you.

**Comment by areplogle-reverb** [comment]
Here's an example - agent.yaml
alert:
```
	Description    :	Containers Should Not Run with AllowPrivilegeEscalation
	File           :	clusters/infra/services/kiam/agent.yaml
	Line           :	1
	Severity       :	HIGH
```

agent.yaml 
```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: kiam-agent
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kiam
        role: agent
        restart: x
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
        - name: ssl-certs
          hostPath:
            # for AWS linux or RHEL distros
            path: /etc/pki/ca-trust/extracted/pem/
            #path: /usr/share/ca-certificates
        - name: tls
          secret:
            secretName: kiam-agent-tls
        - name: xtables
          hostPath:
            path: /run/xtables.lock
            type: FileOrCreate
      containers:
        - name: kiam
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          image: quay.io/uswitch/kiam:v3.6
          imagePullPolicy: Always
          command:
            - /kiam
          args:
            - agent
            - --iptables
            - --host-interface=eni+
            - --json-log
            - --port=8181
            - --cert=/etc/kiam/tls/agent.pem
            - --key=/etc/kiam/tls/agent-key.pem
            - --ca=/etc/kiam/tls/ca.pem
            - --server-address=kiam-server:9443
            - --gateway-timeout-creation=1s
            - --statsd=$(STATSD_HOST):8125
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: STATSD_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          volumeMounts:
            - mountPath: /etc/ssl/certs
              name: ssl-certs
            - mountPath: /etc/kiam/tls
              name: tls
            - mountPath: /var/run/xtables.lock
              name: xtables
          livenessProbe:
            httpGet:
              path: /ping
              port: 8181
            initialDelaySeconds: 3
            periodSeconds: 3
```
